export const eras = [
  {
    title: 'Homework',
    coverUrl: '/homework.jpeg',
    artists: [
      { name: 'Alan Braxe', artistId: '24JRvbKfTcF2x7c2kCCJrW' },
      { name: 'Basement Jaxx', artistId: '4YrKBkKSVeqDamzBPWVnSJ' },
      { name: 'Cassius', artistId: '4sf3QZW8a3xZ14IGsOAzoy' },
      { name: 'Demon', artistId: '4LiDDSfUo671okhAa6OSHY' },
      { name: 'DJ Falcon', artistId: '7mLoDOOVW8VlPUTii10xH5' },
      { name: 'Étienne de Crécy', artistId: '78YRbJhMi5kXKruiQGCJo7' },
      { name: 'Fred Falke', artistId: '0AfNNw1LS2i9KW4icd7inD' },
      { name: 'Ian Pooley', artistId: '1m4GViPjIy4T8Pd0Iz6hRS' },
      { name: 'Modjo', artistId: '0AkpPlFLnr0VQwZQeMGht0' },
      { name: 'Raw Man', artistId: '7q3TH1mtB9tokEPWvoKFSv' },
      { name: 'Tiger & Woods', artistId: '0AEi1DK5ehyvkZzOUlqEVz' },
      { name: 'DJ Sneak', artistId: '5He9yPmPv0Du9hASUlTUjr' },
    ],
  },
  {
    title: 'Alive 1997',
    coverUrl: '/alive_1997.png',
    artists: [
      { name: 'Brodinski', artistId: '0ZurilbRp6KwW6dpaw4pEK' },
      { name: 'Erol Alkan', artistId: '3jQ8hpdQo3TCEnb5gmOtH5' },
      { name: 'Felix da Housecat', artistId: '4rC8J4M4aOqsQSCP4yoyJI' },
      { name: 'Gesaffelstein', artistId: '3hteYQFiMFbJY7wS0xDymP' },
      { name: 'Laurent Garnier', artistId: '3y1SoTOdrmRNTBVph5T0VZ' },
      { name: 'Miss Kittin', artistId: '3QhNv79NoIvarU6N57GBzL' },
      { name: 'Raito', artistId: '5RXdPHNmsB6OQn8rUyRQtl' },
      { name: 'The Chemical Brothers', artistId: '1GhPHrq36VKCY3ucVaZCfo' },
      { name: 'The Hacker', artistId: '763V8ZisRsw5kCoquzKTUp' },
      { name: 'Tracques', artistId: '0KGRYzPoDc1CGjwJ8RPACK' },
    ],
  },
  {
    title: 'Discovery',
    coverUrl: '/discovery.png',
    artists: [
      { name: 'Bag Raiders', artistId: '6fXEqmGQEt6ONuqVmwrN46' },
      { name: 'Breakbot', artistId: '0iui2Be5CP8EWxvHYsVspL' },
      { name: 'Classixx', artistId: '0vUTfcBDZZo2OUQJci5UNZ' },
      { name: 'Cut Copy', artistId: '4EENT7N7rCBwrddM3s0vFS' },
      { name: 'Darius', artistId: '5vfEaoOBcK0Lzr07WN8KaK' },
      { name: 'Hystereo', artistId: '122CqDpvVy1fMI6BRd1UIg' },
      { name: 'Les Rythmes Digitales', artistId: '02zMQvIvPXbVOLDdFqbFUn' },
      { name: 'Madeon', artistId: '4pb4rqWSoGUgxm63xmJ8xc' },
      { name: 'Miami Horror', artistId: '0Z5pcmXDCKTrFWLnDChC37' },
      { name: 'Mylo', artistId: '5YjEVrNMrIRw2xGbjTN6Ti' },
      { name: 'Oliver', artistId: '0NDElNqwGRCmsYIQFapp6K' },
      { name: 'Sam Gellaitry', artistId: '07UJz804RJxqNvxFXC3h9H' },
      { name: 'The Avalanches', artistId: '3C8RpaI3Go0yFF9whvKoED' },
    ],
  },
  {
    title: 'Interstella 5555',
    coverUrl: '/interstella.webp',
    artists: [
      { name: 'CFCF', artistId: '73IRHBhotETMmgvRCEyTCS' },
      { name: 'ev.exi', artistId: '625cTtpQZkHRwLwEtpVbA1' },
      { name: 'FIBRE', artistId: '4TTEh9cj0iUXFJFBHsysF4' },
      { name: 'Haywyre', artistId: '7aUSp5cOZlwEtd5zPC795k' },
      { name: 'MACROSS 82-99', artistId: '5C8KyBfvAz9PSaOd30eIow' },
      { name: 'Mere Notilde', artistId: '2d3wstlwe427Q7CamLXlpO' },
      { name: 'MONDO GROSSO', artistId: '4d2zOuYJHBPJTpVblHEKJb' },
      { name: 'Porter Robinson', artistId: '3dz0NnIZhtKKeXZxLOxCam' },
      { name: 'PROUX', artistId: '7AKW9JOP3AkZzGDqwtbUvu' },
      { name: 'Skylar Spence', artistId: '0x0u0jCVf5Jf4DNh45XPXL' },
      { name: 'The Phantom\'s Revenge', artistId: '4PbkB0f0bB7XeKU54QNTwe' },
      { name: 'Unibe@t', artistId: '1h9Qvyu1kcChodIA2z04Jg' },
      { name: 'Yung Bae', artistId: '30FDJPN3RtwJZ20g5YGCRX' },
    ],
  },
  {
    title: 'Human After All',
    coverUrl: '/haa.jpeg',
    artists: [
      { name: 'Boys Noize', artistId: '62k5LKMhymqlDNo2DWOvvv' },
      { name: 'Digitalism', artistId: '2fBURuq7FrlH6z5F92mpOl' },
      { name: 'Does It Offend You, Yeah?', artistId: '4bFfSfCBYpFh37ziXCSqUs' },
      { name: 'Jackson And His Computerband', artistId: '7Jdjjb3kJWyPmV5MbdVdTv' },
      { name: 'Late of the Pier', artistId: '5ZBQea34QfBgEDkcGEKK2b' },
      { name: 'LCD Soundsystem', artistId: '066X20Nz7iquqkkCW6Jxy6' },
      { name: 'Mr. Oizo', artistId: '0b9ukmbg0MO5eMlorcgOwz' },
      { name: 'MSTRKRFT', artistId: '2squZ8HjM4AzR0j6jsPn4a' },
      { name: 'Soulwax', artistId: '43mWhBXSflupNLuNjM5vff' },
      { name: 'The Bloody Beetroots', artistId: '0QJKELJZZuLAjqLOOixJm5' },
      { name: 'The Presets', artistId: '1zTAQ6zkGz2L2i6lfR30EX' },
      { name: 'Vitalic', artistId: '4M84umUNRbZy1mJleyyRM9' },
      { name: 'ZZT', artistId: '2gv0vhtUiUJeGcYkTybo7G' },
    ],
  },
  {
    title: 'Alive 2007 / Ed Banger',
    coverUrl: '/alive_2007.jpeg',
    artists: [
      { name: 'Alex Metric', artistId: '6RDNTAgm2s6ae71nXWGnJD' },
      { name: 'Birdy Nam Nam', artistId: '4e7qJTThm5uI3CplqZObfT' },
      { name: 'Feadz', artistId: '7JZVTmKriBVQOShSmN4d8I' },
      { name: 'Justice', artistId: '1gR0gsQYfi6joyO1dlp76N' },
      { name: 'Lemaitre', artistId: '4CTKqs11Zgsv8EZTVzx764' },
      { name: 'Para One', artistId: '5MRONaryo2z75lLiuJ0NWJ' },
      { name: 'SebastiAn', artistId: '5tOWIviwLM1EIqGAbF8VSU' },
      { name: 'Shinichi Osawa', artistId: '0s9KIyjWtFcsRdKtMECxFp' },
      { name: 'Siriusmo', artistId: '22680B8sUdq6bL6nQaJfwg' },
      { name: 'Surkin', artistId: '1XqqyIQYMonHgllb1uysL3' },
      { name: 'Uppermost', artistId: '58UpHBCQ1Jj67DJsR7Qyqg' },
      { name: 'Yuksek', artistId: '2ePIzx9NjxplS724QMZtsf' },
      { name: '80KIDZ', artistId: '6ah9gnwgMJ1PMKhkKOwH1D' },
    ],
  },
  {
    title: 'Hypnotize U',
    coverUrl: '/hypnotize.jpg',
    artists: [
      { name: 'C2C', artistId: '28INUgyzTTRbvSphrJbgZ2' },
      { name: 'DJ Mehdi', artistId: '5ffMSKGQRhetAjBjEgkRun' },
      { name: 'DSL', artistId: '1NxmqVpjEvr3TvCchszQDx' },
      { name: 'Hocus Pocus', artistId: '1D5DI6S5zIiGPBf1IAuAJh' },
      { name: 'Outlines', artistId: '7xgpZefXaE1gldPF0XKbvc' },
      { name: 'Teriyaki Boyz', artistId: '7HBai5xymOxIWoMWvWshe1' },
      { name: 'The Neptunes', artistId: '0KuF7reCTOZwV7YJnHQqgr' },
      { name: 'Turntablerocker', artistId: '6Svhb1vO5IFId41F9zIOiN' },
    ],
  },
  {
    title: 'TRON: Legacy',
    coverUrl: '/tron.jpeg',
    artists: [
      { name: 'Anoraak', artistId: '2DfP0hQCCFmZHjstSE8yXC' },
      { name: 'College', artistId: '11TlWPqyDFLHGccTFQhcc6' },
      { name: 'Danger', artistId: '2o3U0ld93tHYowkoari4Vi' },
      { name: 'DatA', artistId: '75QkeG5yBHVCybZurCrMa8' },
      { name: 'Grum', artistId: '3VEqFWRt47xQAZJMBF3duQ' },
      { name: 'Home', artistId: '2exebQUDoIoT0dXA8BcN1P' },
      { name: 'Kavinsky', artistId: '0UF7XLthtbSF2Eur7559oV' },
      { name: 'Lifelike', artistId: '3sa5sqxJqYjDZhGxmo4Ko5' },
      { name: 'M83', artistId: '63MQldklfxkjYDoUE4Tppz' },
      { name: 'Midnight Juggernauts', artistId: '2tGIh9kwbXuko0z3BTldBx' },
      { name: 'Neon Indian', artistId: '0KydPQPUUoTNhmiHKOg5Er' },
      { name: 'Starcadian', artistId: '3I0ceM8qfqhCKGepaswmVg' },
      { name: 'The Glitch Mob', artistId: '3a9qv6NLHnsVxJUtKOMHvD' },
    ],
  },
  {
    title: 'R3CONF1GUR3D',
    coverUrl: '/reconfigured.jpeg',
    artists: [
      { name: 'Carpenter Brut', artistId: '1l2oLiukA9i5jEtIyNWIEP' },
      { name: 'DEADLIFE', artistId: '6YAOorJSNGWyH8m9N7cDeX' },
      { name: 'Magic Sword', artistId: '6PzFRXjgGHQw6K4WeERMK1' },
      { name: 'NERO', artistId: '4uRYpUQZrNrY5t8tAv3XrD' },
      { name: 'Perturbator', artistId: '244uLu9lkdw39BJwlul3k8' },
      { name: 'Prince 85', artistId: '6ADNjKrreUUc181zsy4Cte' },
      { name: 'The M Machine', artistId: '62rW7FjQy7clhBDHuumg22' },
      { name: 'The Toxic Avenger', artistId: '5zExRf0VQCl3GO4Jrj8r0s' },
    ],
  },
  {
    title: 'Random Access Memories',
    coverUrl: '/ram.png',
    artists: [
      { name: 'Aeroplane', artistId: '31CtLHmSL7Oa7TPU9YyBEu' },
      { name: 'Air', artistId: '1P6U1dCeHxPui5pIrGmndZ' },
      { name: 'Chic', artistId: '0Xf8oDAJYd2D0k3NLI19OV' },
      { name: 'Chilly Gonzales', artistId: '0qudezVgvl4Chd9BgNFB83' },
      { name: 'Chromeo', artistId: '2mV8aJphiSHYJf43DxL7Gt' },
      { name: 'Dabeull', artistId: '7sw3xJMTpdcpfssx17hfrb' },
      { name: 'FKJ', artistId: '2FwDTncULUnmANIh7qKa5z' },
      { name: 'Flight Facilities', artistId: '1lc8mnyGrCLtPhCoWjRxjM' },
      { name: 'Giorgio Moroder', artistId: '6jU2Tt13MmXYk0ZBv1KmfO' },
      { name: 'Holy Ghost!', artistId: '2Vhc7Y0Kc6HzMC6glKM4h6' },
      { name: 'Jamiroquai', artistId: '6J7biCazzYhU3gM9j1wfid' },
      { name: 'Jungle', artistId: '59oA5WbbQvomJz2BuRG071' },
      { name: "L'Imperatrice", artistId: '4PwlsrN0t5mLN0C827cbEU' },
      { name: 'Poolside', artistId: '5szdY7KaSi7epwyffrbV8c' },
      { name: 'Todd Terje', artistId: '49gaZqfow2v8EEQmjGyEIw' },
      { name: 'TWRP', artistId: '6N3egqZ7OtcYYXyU6PBdNr' },
    ],
  },
  {
    title: 'Starboy',
    coverUrl: '/starboy.jpg',
    artists: [
      { name: 'Charlotte Gainsbourg', artistId: '2rBcvLKWCZs9w1qIWv560v' },
      { name: 'Chateau Marmont', artistId: '4IQ782VL9bK0q2Judy9mIF' },
      { name: 'Club cheval', artistId: '3sFn8HRnBP6g4twNNy9Tzz' },
      { name: 'Depeche Mode', artistId: '762310PdDnwsDxAQxzQkfX' },
      { name: 'GENER8ION', artistId: '5xXSrTidFvVRJmiam2Zh1o' },
      { name: 'Juliette Armanet', artistId: '61CPKXT0bcKj8MKTNTMOXa' },
      { name: 'KAYTRANADA', artistId: '6qgnBH6iDM91ipVXv28OMu' },
      { name: 'Sébastien Tellier', artistId: '23ymPLjbtAMzTJS2qRtQ8Z' },
      { name: 'The Weeknd', artistId: '1Xyo4u8uXC1ZmMpatF05PJ' },
      { name: 'Woodkid', artistId: '44TGR1CzjKBxSHsSEy7bi9' },
    ],
  },
  {
    title: 'Overnight / Kitsuné',
    coverUrl: '/overnight.jpg',
    artists: [
      { name: 'CSS', artistId: '2K13AVg3bFpHSxDM1vJ0qA' },
      { name: 'Das Pop', artistId: '6HvBsTSctQ8SGUzzfnMPcV' },
      { name: 'Empire of the Sun', artistId: '67hb7towEyKvt5Z8Bx306c' },
      { name: 'Friendly Fires', artistId: '3mZqziCJj4pq3P2VBpmK6p' },
      { name: 'Gemini Club', artistId: '2aCPI1cQHluLnMHkndCL4L' },
      { name: 'Hey Champ!', artistId: '5s1MYt4IRlnpon0BWc7R8p' },
      { name: 'Jamaica', artistId: '5UCFEKPsy3gDKElikr5vg9' },
      { name: 'Jupiter', artistId: '7yIZvf93cvym5UEV2IGd8D' },
      { name: 'Metronomy', artistId: '54QMjE4toDfiCryzYWCpXX' },
      { name: 'Parcels', artistId: '3oKRxpszQKUjjaHz388fVA' },
      { name: 'Phoenix', artistId: '1xU878Z1QtBldR7ru9owdU' },
      { name: 'The Shoes', artistId: '6buUuVTdxxAe5ODJtKZ4hP' },
      { name: 'The Strokes', artistId: '0epOFNiUfyON9EYx7Tpr6V' },
      { name: 'The Twelves', artistId: '6IZEHKUV146uXaXOMKfcqK' },
      { name: 'The Whip', artistId: '4M2H1fDQR5ygAi7MMOVxAA' },
      { name: 'Two Door Cinema Club', artistId: '536BYVgOnRky0xjsPT96zl' },
      { name: 'Van She', artistId: '4FTDSkWpchgZy2axPEGDJW' },
    ],
  },
  {
    title: 'Musique',
    artists: [
      { name: 'A-Trak', artistId: '3TaUSUXn41GixL7zbvrIDt' },
      { name: 'Calvin Harris (2007-09 + Funk way)', artistId: '7CajNmpbOovFoOoasH2HaY' },
      { name: 'Caravan Palace', artistId: '37J1PlAkhRK7yrZUtqaUpQ' },
      { name: 'DJ Koze', artistId: '1kR99O4MgSTasyeJh8UFCg' },
      { name: 'Fatboy Slim', artistId: '4Y7tXHSEejGu1vQ9bwDdXW' },
      { name: 'Gigamesh', artistId: '1Bo8Afb2Qbjs4x6kJHyjle' },
      { name: 'Gorillaz', artistId: '3AA28KZvwAUcZuOKwyblJQ' },
      { name: 'Mirwais', artistId: '0Ohm3LvFp7wzkvMeiTDPKQ' },
      { name: 'Röyksopp', artistId: '5nPOO9iTcrs9k6yFffPxjH' },
      { name: 'Tame Impala', artistId: '5INjqkS1o8h1imAzPqGZBb' },
      { name: 'The Knocks', artistId: '2x7EATekOPhFGRx3syMGEC' },
    ],
  },
];
